export const breadcrumbNameMap: Record<
  string,
  { name: string; isLeaf?: boolean }
> = {
  "/home/shop": { name: "门店管理" },
  "/home/shop/shopCreate": { name: "新建门店" },
  "/home/shop/view": { name: "查看门店" },
  "/home/shop/shopEdit": { name: "编辑门店", isLeaf: true },
  "/home/employee": { name: "员工管理" },
  "/home/employee/create": { name: "新建员工" },
  "/home/employee/view": { name: "查看员工" },
  "/home/employee/edit": { name: "编辑员工", isLeaf: true },
  "/home/scenicSpot": { name: "景点管理" },
  "/home/scenicSpot/create": { name: "新建景点" },
  "/home/scenicSpot/view": { name: "查看景点" },
  "/home/scenicSpot/edit": { name: "编辑景点", isLeaf: true },
  "/home/combo": { name: "套餐管理" },
  "/home/combo/create": { name: "发布套餐", isLeaf: true },
  "/home/combo/view": { name: "查看套餐" },
  "/home/combo/edit": { name: "编辑套餐", isLeaf: true },
  "/home/comboService": { name: "服务列表" },
  "/home/comboService/create": { name: "新增服务", isLeaf: true },
  "/home/comboService/view": { name: "查看服务" },
  "/home/comboService/edit": { name: "编辑服务", isLeaf: true },
  "/home/goods": { name: "商品库" },
  "/home/goods/create": { name: "发布商品", isLeaf: true },
  "/home/goods/edit": { name: "编辑商品", isLeaf: true },
  "/home/storeGoods": { name: "门店商品" },
  "/home/storeGoods/show": { name: "查看商品", isLeaf: true },
  "/home/storeData": { name: "门店资料" },
  "/home/storeWork": { name: "门店作品" },
  "/home/storeWork/create": { name: "新增作品", isLeaf: true },
  "/home/storeWork/edit": { name: "编辑作品", isLeaf: true },
  "/home/customerManagement": { name: "客户管理" },
  "/home/customerManagement/create": { name: "新增客户", isLeaf: true },
  "/home/customerManagement/edit": { name: "编辑客户", isLeaf: true },
  "/home/orderManager": { name: "订单管理" },
  "/home/orderManager/create": { name: "新增订单", isLeaf: true },
  "/home/orderManager/detail": { name: "订单详情", isLeaf: true },
};
